
    create table aluno (
        id bigint generated by default as identity,
        matricula varchar(255),
        nome varchar(255),
        primary key (id)
    );

    create table avaliacao (
        n1 float(53),
        n2 float(53),
        aluno_id bigint not null,
        disciplina_id bigint not null,
        primary key (aluno_id, disciplina_id)
    );

    create table curso (
        id bigint generated by default as identity,
        duracao varchar(255),
        nome varchar(255),
        primary key (id)
    );

    create table departamento (
        id bigint generated by default as identity,
        nome varchar(255),
        primary key (id)
    );

    create table disciplina (
        id bigint generated by default as identity,
        carga_horaria integer not null,
        nome varchar(255),
        curso_id bigint,
        professor_id bigint,
        primary key (id)
    );

    create table endereco (
        id bigint generated by default as identity,
        cidade varchar(255),
        estado varchar(255),
        rua varchar(255),
        primary key (id)
    );

    create table matricula (
        semestre varchar(255),
        aluno_id bigint not null,
        disciplina_id bigint not null,
        primary key (aluno_id, disciplina_id)
    );

    create table professor (
        id bigint generated by default as identity,
        especialidade varchar(255),
        nome varchar(255),
        departamento_id bigint,
        endereco_id bigint,
        primary key (id)
    );

    alter table if exists professor 
       drop constraint if exists UKcg9si6hurvcdp70e6otox1s20;

    alter table if exists professor 
       add constraint UKcg9si6hurvcdp70e6otox1s20 unique (endereco_id);

    alter table if exists avaliacao 
       add constraint FK4paciv5p2nhnh8jl2qvw72efg 
       foreign key (aluno_id, disciplina_id) 
       references matricula;

    alter table if exists disciplina 
       add constraint FKkhdiw1swjoa2ml3md0mt8g4sf 
       foreign key (curso_id) 
       references curso;

    alter table if exists disciplina 
       add constraint FKoqie7f1kx32b1atco9fpgxd7g 
       foreign key (professor_id) 
       references professor;

    alter table if exists matricula 
       add constraint FKsmkrefmwkwfyod36k45jf1rr5 
       foreign key (aluno_id) 
       references aluno;

    alter table if exists matricula 
       add constraint FK9q3agcy53y27hpojb8c9xyjc1 
       foreign key (disciplina_id) 
       references disciplina;

    alter table if exists professor 
       add constraint FK9p7i98r41ujcw10nsu9qlcjak 
       foreign key (departamento_id) 
       references departamento;

    alter table if exists professor 
       add constraint FKf3kci47kb5v2ma4dsqmk6cmnb 
       foreign key (endereco_id) 
       references endereco;
