
    create table usuario (
        id bigint generated by default as identity,
        password varchar(255) not null,
        role varchar(255),
        username varchar(255) not null,
        aluno_id bigint,
        professor_id bigint,
        primary key (id)
    );

    alter table if exists usuario 
       drop constraint if exists UK863n1y3x0jalatoir4325ehal;

    alter table if exists usuario 
       add constraint UK863n1y3x0jalatoir4325ehal unique (username);

    alter table if exists usuario 
       drop constraint if exists UKr88f5i8wsd5xfc6m3wj9pi6nm;

    alter table if exists usuario 
       add constraint UKr88f5i8wsd5xfc6m3wj9pi6nm unique (aluno_id);

    alter table if exists usuario 
       drop constraint if exists UKs0m6n1glt6ol07lx5qus03k3h;

    alter table if exists usuario 
       add constraint UKs0m6n1glt6ol07lx5qus03k3h unique (professor_id);

    alter table if exists usuario 
       add constraint FKn358c9r8f52y6j0up3wou1nli 
       foreign key (aluno_id) 
       references aluno;

    alter table if exists usuario 
       add constraint FKl2a5bcsu8sj88fo42bx8os5g3 
       foreign key (professor_id) 
       references professor;
